# Generated by Django 3.2.19 on 2023-05-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_auto_20230514_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='fecha_llegada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='numero_lote',
            field=models.CharField(max_length=40),
        ),
    ]
