# Generated by Django 3.2.19 on 2023-05-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_auto_20230516_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='numero_lote',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
