# Generated by Django 3.2.18 on 2023-05-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_productos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.CharField(blank=True, default=True, max_length=150, null=True),
        ),
    ]
